use /var/cache/lxc to store all image files

diff --git a/scripts/cookbooks/lxc/templates/default/lxc-centos-6 b/scripts/cookbooks/lxc/templates/default/lxc-centos-6
--- a/scripts/cookbooks/lxc/templates/default/lxc-centos-6
+++ b/scripts/cookbooks/lxc/templates/default/lxc-centos-6
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-echo "Creating natty node..."
+echo "Creating centos-6 node..."
 
-configure_ubuntu()
+configure_centos()
 {
     rootfs=$1
     hostname=$2
 
-	# disable selinux in ubuntu
+	# disable selinux in centos
     mkdir -p $rootfs/selinux
     echo 0 > $rootfs/selinux/enforce
 
@@ -19,7 +19,6 @@ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCguB7XL3ARzLZYLsIMZe4UUO371m+H5C6V8MhtmSl
 	EOF
 
 	# copy host resolve 
-    rm $rootfs/etc/resolv.conf
     cp /etc/resolv.conf $rootfs/etc/resolv.conf
 
 	# add default route to host
@@ -28,10 +27,6 @@ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCguB7XL3ARzLZYLsIMZe4UUO371m+H5C6V8MhtmSl
 route add default gw <%= node.network.gateway_ip %>
 exit 0
 EOF
-
-    # disable selinux in ubuntu
-    mkdir -p $rootfs/selinux
-    echo 0 > $rootfs/selinux/enforce
 
     # set the hostname
     cat <<EOF > $rootfs/etc/hostname
@@ -42,35 +37,67 @@ EOF
 127.0.0.1 localhost $hostname
 EOF
 
-    # suppress log level output for udev
-	sed -i "s/=\"err\"/=0/" $rootfs/etc/udev/udev.conf
+    cat <<EOF > $rootfs/etc/init/console.conf
+# console - mingetty
+#
+# This service maintains a console on tty1 from the point the system is
+# started until it is shut down again.
 
-	# remove jobs for consoles 5 and 6 since we only create 4 consoles in
-	# this template
-	rm -f $rootfs/etc/init/tty{5,6}.conf
+start on stopped rc RUNLEVEL=[2345]
+stop on runlevel [!2345]
 
+respawn
+exec /sbin/mingetty console
+EOF
+
+	cat <<EOF > $rootfs/etc/fstab
+none /dev/pts devpts defaults 0 0
+EOF
+
+	[ ! -f $rootfs/etc/init/kexec-disable.conf ] || mv $rootfs/etc/init/kexec-disable.conf $rootfs/etc/init/kexec-disable.conf.orig
+	sed -i -e 's:/sbin/start_udev:#/sbin/start_udev:' $rootfs/etc/rc.d/rc.sysinit
+	
+	sed -i -e 's:\(Defaults *requiretty\):# \1:' $rootfs/etc/sudoers
+		
+	# create necessary devices
+	rm $rootfs/dev/null
+	mknod -m 666 $rootfs/dev/null c 1 3
+	mknod -m 666 $rootfs/dev/random c 1 8
+	mknod -m 666 $rootfs/dev/urandom c 1 9
+	mkdir -m 755 $rootfs/dev/pts
+	mknod -m 666 $rootfs/dev/tty c 5 0
+	mknod -m 666 $rootfs/dev/tty0 c 4 0
+	mknod -m 666 $rootfs/dev/tty1 c 4 1
+	mknod -m 666 $rootfs/dev/tty2 c 4 2
+	mknod -m 666 $rootfs/dev/tty3 c 4 3
+	mknod -m 666 $rootfs/dev/tty4 c 4 4
+	mknod -m 600 $rootfs/dev/console c 5 1
+	mknod -m 666 $rootfs/dev/full c 1 7
+	mknod -m 600 $rootfs/dev/initctl p
+
+	# change root password
     echo "Set root password to 'root'"
     echo "root:root" | chroot $rootfs chpasswd
 
     return 0
 }
 
-copy_ubuntu()
+copy_centos()
 {
     cache=$1
     arch=$2
     rootfs=$3
 
-    # make a local copy of the miniubuntu
+    # make a local copy of the minicentos
     echo "Extracting rootfs image to $rootfs ..."
     mkdir $rootfs
-    tar zxf $cache/natty-$arch.tar.gz -C $rootfs || return 1
+    tar zxf $cache/centos-6-$arch.tar.gz -C $rootfs || return 1
     return 0
 }
 
-install_ubuntu()
+install_centos()
 {
-    cache="/var/cache/lxc/ubuntu"
+    cache="/var/cache/lxc"
     rootfs=$1
     mkdir -p /var/lock/subsys/
     (
@@ -92,12 +119,12 @@ install_ubuntu()
 	echo "Checking image cache in $cache/rootfs-$arch ... "
 	if [ ! -e "$cache/rootfs-$arch" ]; then
 	    if [ $? -ne 0 ]; then
-		echo "Failed to download 'ubuntu base'"
+		echo "Failed to download 'centos base'"
 		return 1
 	    fi
 	fi
 
-	copy_ubuntu $cache $arch $rootfs
+	copy_centos $cache $arch $rootfs
 	if [ $? -ne 0 ]; then
 	    echo "Failed to copy rootfs"
 	    return 1
@@ -125,14 +152,27 @@ lxc.rootfs = $rootfs
 lxc.mount  = $path/fstab
 
 lxc.cgroup.devices.deny = a
+
+lxc.cgroup.devices.allow = b 1:0 rwm
+lxc.cgroup.devices.allow = b 1:1 rwm
+lxc.cgroup.devices.allow = c 1:1 rwm
+lxc.cgroup.devices.allow = c 1:2 rwm
+lxc.cgroup.devices.allow = c 1:4 rwm
+lxc.cgroup.devices.allow = c 1:6 rwm
+lxc.cgroup.devices.allow = c 1:7 rwm
+lxc.cgroup.devices.allow = c 1:11 rwm
+
+lxc.cgroup.devices.allow = c 2:* rwm
+lxc.cgroup.devices.allow = c 3:* rwm
+
 # /dev/null and zero
 lxc.cgroup.devices.allow = c 1:3 rwm
 lxc.cgroup.devices.allow = c 1:5 rwm
 # consoles
 lxc.cgroup.devices.allow = c 5:1 rwm
 lxc.cgroup.devices.allow = c 5:0 rwm
-# lxc.cgroup.devices.allow = c 4:0 rwm
-# lxc.cgroup.devices.allow = c 4:1 rwm
+lxc.cgroup.devices.allow = c 4:0 rwm
+lxc.cgroup.devices.allow = c 4:1 rwm
 # /dev/{,u}random
 lxc.cgroup.devices.allow = c 1:9 rwm
 lxc.cgroup.devices.allow = c 1:8 rwm
@@ -149,8 +189,8 @@ sysfs           $rootfs/sys          sysfs defaults  0 0
 EOF
 
     if [ $? -ne 0 ]; then
-	echo "Failed to add configuration"
-	return 1
+		echo "Failed to add configuration"
+		return 1
     fi
 
     return 0
@@ -158,7 +198,7 @@ EOF
 
 clean()
 {
-    cache="/var/cache/lxc/ubuntu"
+    cache="/var/cache/lxc"
 
     if [ ! -e $cache ]; then
 	exit 0
@@ -211,12 +251,6 @@ if [ ! -z "$clean" -a -z "$path" ]; then
     exit 0
 fi
 
-type debootstrap
-if [ $? -ne 0 ]; then
-    echo "'debootstrap' command is missing"
-    exit 1
-fi
-
 if [ -z "$path" ]; then
     echo "'path' parameter is required"
     exit 1
@@ -229,15 +263,15 @@ fi
 
 rootfs=$path/rootfs
 
-install_ubuntu $rootfs
+install_centos $rootfs
 if [ $? -ne 0 ]; then
-    echo "failed to install ubuntu"
+    echo "failed to install centos"
     exit 1
 fi
 
-configure_ubuntu $rootfs $name
+configure_centos $rootfs $name
 if [ $? -ne 0 ]; then
-    echo "failed to configure ubuntu for a container"
+    echo "failed to configure centos for a container"
     exit 1
 fi
 
